[package]
name = "wasvy_macros"
version = "0.0.6"
edition = "2024"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.36"
syn = { version = "2.0.87", features = ["full", "extra-traits"] }
proc-macro-crate = "3.1.0"
wit-parser = "0.243.0"
